version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chat_manager_db
    restart: unless-stopped
    # Load environment variables from parent .env
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: chat_manager_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata: {}
  redisdata: {} 